# Generated by Django 5.0 on 2023-12-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_subscriber_emailtemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
